### ISSUE TITLE
Error: connection timed out at Socket

### ISSUE THREAD

**Issue by J-Wilkening** [miguelangelopereira/azuremonitor2syslog#11]
Hi. I am running multiple eventhub2Syslog instance in one azure function app. I am getting multiple error messages like: 

`2021-11-04T11:30:42.015 [Error] Executed 'Functions.XXX' (Failed, Id=XXX, Duration=20ms)
node exited with code 1
 LanguageWorkerConsoleLog[error] Worker XXX uncaught exception (learn more: https://go.microsoft.com/fwlink/?linkid=2097909 ):
 Error: connection timed out at Socket.<anonymous>
(D:\home\site\wwwroot\node_modules\syslog-client\index.js:276:14)
at Object.onceWrapper (events.js:421:28)
at Socket.emit (events.js:315:20)
at Socket._onTimeout (net.js:483:8)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)`

Can anyone figure out where this is coming from? Thanks for assistance

**Comment by devtrf** [comment]
@J-Wilkening were you able to deploy this solution presently, and was there a lot of deviation from the initial config as described on the README?

This is still the only setup Microsoft documentation points to, but I've been fairly unsuccessful at getting this to work.
